"""Control-Feedback BOM packaging (JSON-LD + PROV-O + Data Integrity).

Phase 1: address refs + DID attribution.
Phase 1b: eddsa-jcs-2022 proof via ``sign_execution_bom``.
Stage lineage: ``prov:wasDerivedFrom`` between Invoice stage content ids.
Phase 2b / §6d: entity ``@id`` prefers HTTP URI; ``ni:`` as ``contentId``;
signed JSON omits ``*_cid`` field names (``invoice_uri`` / ``log_uri`` only).
"""
from __future__ import annotations

from typing import Any

from cats.network.cas.content_ref import content_uri, is_http_uri
from cats.network.feedback.data_integrity import (
    DATA_INTEGRITY_CONTEXT,
    sign_document,
    verify_document,
)
from cats.network.identity.node_did import (
    did_key_verification_method,
    load_node_signing_material,
)

EXECUTOR_RUN_ID = '#executorRun'

# Compact JSON-LD context for ExecutionBom (§6d: no cats:*_cid terms).
_EXECUTION_BOM_CONTEXT: list[Any] = [
    'https://www.w3.org/ns/prov#',
    {
        'cats': 'https://dynamicalsystemsgroup.github.io/cats/ns#',
        'invoice_uri': 'cats:invoice_uri',
        'log_uri': 'cats:log_uri',
        'node_did': 'cats:node_did',
        'stageLineage': 'cats:stageLineage',
        'contentId': 'cats:contentId',
    },
]


def attach_node_did(package: dict, node_did: str) -> dict:
    """Set ``node_did`` on a feedback package (DID attribution)."""
    package['node_did'] = node_did
    return package


def _entity_id(content_id: str, *, uri: str | None = None) -> dict[str, Any]:
    """PROV entity ref: prefer HTTP URI ``@id``; keep ``ni:``/CID as ``contentId``."""
    resolved = uri
    if resolved is None:
        resolved = content_uri(content_id)
    if resolved and is_http_uri(resolved):
        return {'@id': resolved, 'contentId': content_id}
    if is_http_uri(content_id):
        return {'@id': content_id}
    # Legacy CID / bare id: keep historical ``ipfs://`` @id shape (no extra keys).
    return {'@id': f'ipfs://{content_id}'}


def _stage_entity(
    content_id: str,
    *,
    uri: str | None = None,
    derived_from: str | None = None,
    derived_from_uri: str | None = None,
    generated_by: bool = True,
) -> dict[str, Any]:
    entity: dict[str, Any] = {
        **_entity_id(content_id, uri=uri),
        '@type': 'prov:Entity',
    }
    if generated_by:
        entity['prov:wasGeneratedBy'] = {'@id': EXECUTOR_RUN_ID}
    if derived_from:
        entity['prov:wasDerivedFrom'] = _entity_id(
            derived_from, uri=derived_from_uri
        )
    return entity


def build_execution_bom(
    *,
    log_id: str,
    invoice_id: str,
    node_did: str | None = None,
    order_id: str | None = None,
    input_data_id: str | None = None,
    ingress_data_id: str | None = None,
    integration_data_id: str | None = None,
    data_id: str | None = None,
    structure_as_executed_id: str | None = None,
    invoice_uri: str | None = None,
    log_uri: str | None = None,
    order_uri: str | None = None,
    input_data_uri: str | None = None,
    ingress_data_uri: str | None = None,
    integration_data_uri: str | None = None,
    data_uri: str | None = None,
    structure_as_executed_uri: str | None = None,
) -> dict[str, Any]:
    """Build post-execute BOM dict from address refs only (no payloads).

    Matches ControlFeedbackLoop §5: Invoice + log. Structure as-executed nesting
    lives on the Invoice. ``node_did`` is additive Node attribution.

    When stage content ids are provided, ``stageLineage`` lists ``prov:Entity``
    nodes with ``prov:wasDerivedFrom`` along the payload chain.
    ``structure_as_executed`` is generated by the same activity but is not on
    the payload derivation chain.

    §6d: signed JSON carries ``invoice_uri`` / ``log_uri`` only (no
    ``invoice_cid`` / ``log_cid``). Equality stays on entity ``contentId`` /
    URI path hex. Python kwargs use ``*_id`` names holding ``ni:`` / digests.

    Shape is JSON-LD + PROV-O (unsigned until ``sign_execution_bom``).
    BOM content id is minted by the caller and must not appear inside this
    object.
    """
    resolved_invoice_uri = invoice_uri or content_uri(invoice_id)
    resolved_log_uri = log_uri or content_uri(log_id)

    used: list[dict[str, Any]] = []
    if order_id:
        used.append(_entity_id(order_id, uri=order_uri))
    used.append(_entity_id(invoice_id, uri=resolved_invoice_uri))

    activity: dict[str, Any] = {
        '@id': EXECUTOR_RUN_ID,
        '@type': 'prov:Activity',
        'prov:used': used[0] if len(used) == 1 else used,
    }

    bom: dict[str, Any] = {
        '@context': list(_EXECUTION_BOM_CONTEXT),
        '@type': ['prov:Entity', 'cats:ExecutionBom'],
        'prov:wasGeneratedBy': activity,
    }
    if resolved_invoice_uri:
        bom['invoice_uri'] = resolved_invoice_uri
    else:
        # Legacy CID without CAS URI: stash equality id in invoice_uri so
        # readers can still resolve via AddressStore (no invoice_cid key).
        bom['invoice_uri'] = invoice_id
    if resolved_log_uri:
        bom['log_uri'] = resolved_log_uri
    else:
        bom['log_uri'] = log_id

    if node_did is not None:
        attach_node_did(bom, node_did)
        bom['prov:wasAttributedTo'] = {'@id': node_did}

    lineage: list[dict[str, Any]] = []
    if ingress_data_id:
        lineage.append(
            _stage_entity(
                ingress_data_id,
                uri=ingress_data_uri,
                derived_from=input_data_id or None,
                derived_from_uri=input_data_uri,
            )
        )
    if integration_data_id:
        lineage.append(
            _stage_entity(
                integration_data_id,
                uri=integration_data_uri,
                derived_from=ingress_data_id or None,
                derived_from_uri=ingress_data_uri,
            )
        )
    if data_id:
        lineage.append(
            _stage_entity(
                data_id,
                uri=data_uri,
                derived_from=integration_data_id or None,
                derived_from_uri=integration_data_uri,
            )
        )
    if structure_as_executed_id:
        lineage.append(
            _stage_entity(
                structure_as_executed_id,
                uri=structure_as_executed_uri,
                derived_from=None,
            )
        )

    if lineage:
        bom['stageLineage'] = lineage

    return bom


def sign_execution_bom(
    bom: dict[str, Any],
    *,
    cats_home: str | None = None,
) -> dict[str, Any]:
    """Sign an ExecutionBom with eddsa-jcs-2022 using local Node key material.

    Ensures ``bom['node_did']`` matches the signing keyfile DID (and
    ``CAT_NODE_DID`` when set). Extends ``@context`` with the Data Integrity
    v2 context when missing.
    """
    did, private_key = load_node_signing_material(cats_home)
    node = bom.get('node_did')
    if node is None:
        attach_node_did(bom, did)
        bom['prov:wasAttributedTo'] = {'@id': did}
    elif node != did:
        raise ValueError(
            f'bom.node_did ({node!r}) does not match signing DID ({did!r})'
        )

    ctx = bom.get('@context')
    if isinstance(ctx, list):
        if DATA_INTEGRITY_CONTEXT not in ctx:
            bom = {**bom, '@context': list(ctx) + [DATA_INTEGRITY_CONTEXT]}
    elif ctx is None:
        bom = {
            **bom,
            '@context': list(_EXECUTION_BOM_CONTEXT) + [DATA_INTEGRITY_CONTEXT],
        }
    else:
        bom = {
            **bom,
            '@context': [ctx, DATA_INTEGRITY_CONTEXT],
        }

    return sign_document(
        bom,
        private_key,
        did_key_verification_method(did),
    )


def verify_execution_bom(bom: dict[str, Any]) -> None:
    """Verify the Data Integrity proof on an ExecutionBom; raise on failure."""
    verify_document(bom)
